### ISSUE TITLE
Android Samsung Browser

### ISSUE THREAD

**Issue by RottWyler** [thingsym/multi-device-switcher#13]
Hi,
Is there a way to add Instagrams / WebView Default Browser under Multi Device Switcher>UserAgent
Thanks Steve

**Comment by thingsym** [comment]
Hi @RottWyler,

You can detect app browser by adding Custom Switcher as inAppBrowser.

Set the theme for Custom Switcher and add the following in-app browser user agent.

```
Instagram, Line, FBAN, FBAV, MicroMessenger
```

FBAN, FBAV => Facebook app
MicroMessenger => WeChat app

Twitter, Slack, and Discord apps cannot be detected individually because they have the same UserAgent as iOS or Android.
