### ISSUE TITLE
Doesn't Work with WordPress 6.4

### ISSUE THREAD

**Issue by williami9sergipe** [thingsym/multi-device-switcher#14]
Today the WordPress update came out, to version 6.4, after updating the site only opens in the Desktop theme, it does not open in the theme selected in the plugin. I reverted to WordPress 6.3.2 and everything worked normally again.

There is possibly some incompatibility of the plugin with WordPress 6.4.

**Comment by thingsym** [comment]
Thank you for your report.

I have confirmed that the theme does not switch. The occurrence conditions have been confirmed on the production environment server and WordPress 6.4 or later.

It did not occur in the development environment or local environment. There seems to be no particular problem with the implementation code. The unit test also passed.

At the moment, I don't know why it only occurs on the production environment server.

The situation is currently difficult to pinpoint, so we will take action as soon as I know.

Until then, if you want to use the Multi Device Switcher plugin, please use it with WordPress 6.3.


日本語:

報告ありがとうございます。

テーマが切り替わらない現象を確認しました。
発生条件は、本番環境サーバと WordPress 6.4 以降で確認しています。

開発環境やローカル環境では、発生しませんでした。
実装コードも特に問題がなさそうなようです。ユニットテストも通りました。

いまのところ、なぜ本番環境サーバだけで生じているのか、原因がわかりません。
現在、特定が難しい状況ですので、分かり次第、対応をしたいと思います。

それまでプラグインを使用する場合は、WordPress 6.3 でお使いください。

**Comment by thingsym** [comment]
This is a related issue.

Since WordPress 6.4, the functions.php of a theme moved to a different location using register_theme_directory is no longer called

https://core.trac.wordpress.org/ticket/59847

**Comment by hiyakake** [comment]
こんにちは。
私が利用させていただいているマルチサイトにおいても同様です。
しばらくはWP6.3にて様子を見たいと思います。
問題解決の方、どうぞよろしくお願いいたします。

**Comment by hiyakake** [comment]
色々試したところはっきりしたのは、エージェントがSPかつ**WordPressが非ログイン状態の時**に、例えば本来SP向けに用意したテーマを読み込むはずが、先にPC向けのテーマ（デフォルトのテーマ）がロードされ内部で同じ関数名の衝突や、header.phpなどのテンプレート改装で定義されている予約済みのテーマファイルがロードされCSS等のパスがおかしくなるということです。

**Comment by thingsym** [comment]
I have confirmed that themes can be switched using Multi Device Switcher in WordPress 6.4.2.
The bug has been fixed in WordPress Core, and Multi Device Switcher now works properly.

Bug report: https://core.trac.wordpress.org/ticket/59847

It seems to have been caused by a change (breaking change) at https://core.trac.wordpress.org/changeset/56635.
The bug is fixed in https://core.trac.wordpress.org/changeset/57129
This issue was resolved in WordPress 6.4.2.


日本語:

WordPress 6.4.2 でテーマが切り替わることを確認しました。
WordPress本体に修正が入り、Multi Device Switcher が正常に動くようになりました。

バグ報告: https://core.trac.wordpress.org/ticket/59847

https://core.trac.wordpress.org/changeset/56635 での変更 (破壊的な変更)で生じたようです。
以下でバグが修正され、https://core.trac.wordpress.org/changeset/57129
WordPress 6.4.2で解消しました。
